spring.application.name=spring-docker-compose-kafka

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.admin.fail-fast=true
spring.kafka.listener.missing-topics-fatal=true
spring.kafka.admin.close-timeout=5000
spring.kafka.admin.operation-timeout=5000